export enum Personality {
  Introvert = 'Introvert',
  Ambivert = 'Ambivert',
  Extravert = 'Extravert',
  INTJ = 'INTJ',
  INTP = 'INTP',
  INFJ = 'INFJ',
  INFP = 'INFP',
  ISTJ = 'ISTJ',
  ISTP = 'ISTP',
  ISFJ = 'ISFJ',
  ISFP = 'ISFP',
  ENTJ = 'ENTJ',
  ENTP = 'ENTP',
  ENFJ = 'ENFJ',
  ENFP = 'ENFP',
  ESTJ = 'ESTJ',
  ESTP = 'ESTP',
  ESFJ = 'ESFJ',
  ESFP = 'ESFP',
}
